# Site settings
title: Mirotic Blog
email: jonguk1221@gmail.com
description: Java Backend Developer
baseurl: ""
url: "http://mirotic91.github.io"

# Social Profiles
github_username: mirotic91

# Build settings
markdown: kramdown
highlighter: rouge
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
